version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000" # This port is only used internally within Docker
    environment:
      - NEXT_PUBLIC_API_URL=https://api.dockendocs.com/api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  mongo-data:
